name: google_translation
description: "Google Translator API Support for Dart"
version: 0.1.3
homepage: https://github.com/phithang711/google_translation

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0